### ISSUE TITLE
some operators don't work

### ISSUE THREAD

**Issue by frehner** [esm-bundle/rxjs#1]
I personally think this is just an issue with how rxjs is written/built, but here's a codepen showing that the `finalize` operator is never fired

https://codesandbox.io/s/hungry-jang-iwdns

**Comment by joeldenning** [comment]
Fixed in https://github.com/esm-bundle/rxjs/commit/c7e4a54c12d2f78f856ebc4e898b29573890770d.

The issue was that rxjs-operators.min.js contained a duplicate version of rxjs itself in it. And apparently the finalize operator only works if the operator's version of rxjs is the same instance as the observable it's being applied to.
